
# jekyll configuration
markdown: redcarpet
permalink: date
safe: false
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

kramdown:
  input: GFM

redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - footnotes
    - superscript

emoji_dir: images/emoji

# Site variables
base_url: /
full_url: http://www.lee-dohm.com
feed_url: feed.xml

tagline: Games and Technology Should Include EVERYone
title: lee-dohm.com

author:
  name: Lee Dohm
  email: lee@lee-dohm.com
  github: lee-dohm

collections:
  - links

sass:
  sass_dir: _sass
