
# jekyll configuration
markdown: KramdownPygments
permalink: date
safe: false
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

kramdown:
  input: GFM

emoji_dir: images/emoji

# Site variables
base_url: /
full_url: http://www.lee-dohm.com
feed_url: feed.xml

title: lee-dohm.com

author:
  name: Lee Dohm
  email: lee@lee-dohm.com
  github: lee-dohm

collections:
  - links
